ALTER TABLE customers
  ADD COLUMN id_card_number VARCHAR(20) NULL AFTER company_name,
  ADD COLUMN is_vat TINYINT DEFAULT 0 AFTER id_card_number,
  ADD COLUMN tax_id VARCHAR(20) NULL AFTER is_vat,
  ADD COLUMN house_number VARCHAR(50) NULL AFTER tax_id,
  ADD COLUMN moo VARCHAR(20) NULL AFTER house_number,
  ADD COLUMN soi VARCHAR(100) NULL AFTER moo,
  ADD COLUMN road VARCHAR(100) NULL AFTER soi,
  ADD COLUMN amphoe VARCHAR(100) NULL AFTER address,
  ADD COLUMN tambon VARCHAR(100) NULL AFTER amphoe,
  ADD COLUMN zipcode VARCHAR(10) NULL AFTER tambon,
  ADD COLUMN username VARCHAR(100) NULL AFTER zipcode,
  ADD COLUMN password_hash VARCHAR(255) NULL AFTER username,
  ADD COLUMN role VARCHAR(50) DEFAULT 'customer' AFTER password_hash,
  ADD COLUMN status ENUM('active','inactive') DEFAULT 'active' AFTER role,
  ADD COLUMN transport_company_id INT NULL AFTER status,
  ADD COLUMN boxes_per_shipment INT DEFAULT 6 AFTER transport_company_id,
  ADD COLUMN sales_person_id INT NULL AFTER boxes_per_shipment,
  ADD COLUMN sales_zone VARCHAR(100) NULL AFTER sales_person_id,
  ADD COLUMN customer_since DATE NULL AFTER sales_zone