CREATE TABLE IF NOT EXISTS sub_customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sub_customer_code VARCHAR(20) NOT NULL UNIQUE,
  parent_customer_id INT NOT NULL,
  company_name VARCHAR(200) NOT NULL,
  id_card_number VARCHAR(20),
  is_vat TINYINT DEFAULT 0,
  tax_id VARCHAR(20),
  house_number VARCHAR(50),
  moo VARCHAR(20),
  soi VARCHAR(100),
  road VARCHAR(100),
  province_id INT,
  amphoe VARCHAR(100),
  tambon VARCHAR(100),
  zipcode VARCHAR(10),
  status ENUM('active','inactive') DEFAULT 'active',
  boxes_per_shipment INT DEFAULT 6,
  sales_person_id INT,
  sales_zone VARCHAR(100),
  customer_since DATE,
  shared_credit_customer_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (parent_customer_id) REFERENCES customers(id),
  FOREIGN KEY (province_id) REFERENCES provinces(id),
  FOREIGN KEY (sales_person_id) REFERENCES employees(id),
  FOREIGN KEY (shared_credit_customer_id) REFERENCES customers(id)
)